package org.booklore.app.specification;

import org.booklore.app.specification.AppBookSpecification;
import org.booklore.model.entity.BookEntity;
import org.junit.jupiter.api.Test;
import org.springframework.data.jpa.domain.Specification;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the author sort specification methods and the
 * {@link AppBookSpecification#isAuthorSort(String)} sentinel check.
 *
 * These tests verify the contract of the specification factory methods
 * without requiring a live database. They ensure:
 * <ul>
 *   <li>isAuthorSort() correctly identifies author sort sentinels</li>
 *   <li>orderByAuthorName() and orderByAuthorSurname() produce non-null specifications</li>
 *   <li>Both ascending/descending variants are supported</li>
 *   <li>The specifications are composable with other specifications via .and()</li>
 * </ul>
 *
 * The actual SQL generated by these specifications is validated by the service-level
 * integration tests that exercise getBooks() end-to-end.
 */
class AppBookSpecificationSortTest {

    @Test
    void isAuthorSort_authorSentinel_returnsTrue() {
        assertTrue(AppBookSpecification.isAuthorSort(AppBookSpecification.SORT_AUTHOR));
    }

    @Test
    void isAuthorSort_authorSurnameSentinel_returnsTrue() {
        assertTrue(AppBookSpecification.isAuthorSort(AppBookSpecification.SORT_AUTHOR_SURNAME));
    }

    @Test
    void isAuthorSort_regularField_returnsFalse() {
        assertFalse(AppBookSpecification.isAuthorSort("addedOn"));
        assertFalse(AppBookSpecification.isAuthorSort("metadata.title"));
        assertFalse(AppBookSpecification.isAuthorSort("metadata.publisher"));
        assertFalse(AppBookSpecification.isAuthorSort("userBookProgress.lastReadTime"));
    }

    @Test
    void isAuthorSort_null_returnsFalse() {
        assertFalse(AppBookSpecification.isAuthorSort(null));
    }

    @Test
    void isAuthorSort_emptyString_returnsFalse() {
        assertFalse(AppBookSpecification.isAuthorSort(""));
    }

    @Test
    void isAuthorSort_similarButWrongSentinel_returnsFalse() {
        assertFalse(AppBookSpecification.isAuthorSort("author"));
        assertFalse(AppBookSpecification.isAuthorSort("__Author__"));
        assertFalse(AppBookSpecification.isAuthorSort("authorSurnameVorname"));
    }

    @Test
    void orderByAuthorName_ascending_returnsNonNullSpec() {
        Specification<BookEntity> spec = AppBookSpecification.orderByAuthorName(true);
        assertNotNull(spec, "orderByAuthorName(true) should not return null");
    }

    @Test
    void orderByAuthorName_descending_returnsNonNullSpec() {
        Specification<BookEntity> spec = AppBookSpecification.orderByAuthorName(false);
        assertNotNull(spec, "orderByAuthorName(false) should not return null");
    }

    @Test
    void orderByAuthorName_composableWithOtherSpecs() {
        Specification<BookEntity> authorSort = AppBookSpecification.orderByAuthorName(true);
        Specification<BookEntity> notDeleted = AppBookSpecification.notDeleted();

        // Should not throw when composed
        Specification<BookEntity> combined = notDeleted.and(authorSort);
        assertNotNull(combined, "Composed specification should not be null");
    }

    @Test
    void orderByAuthorSurname_ascending_returnsNonNullSpec() {
        Specification<BookEntity> spec = AppBookSpecification.orderByAuthorSurname(true);
        assertNotNull(spec, "orderByAuthorSurname(true) should not return null");
    }

    @Test
    void orderByAuthorSurname_descending_returnsNonNullSpec() {
        Specification<BookEntity> spec = AppBookSpecification.orderByAuthorSurname(false);
        assertNotNull(spec, "orderByAuthorSurname(false) should not return null");
    }

    @Test
    void orderByAuthorSurname_composableWithOtherSpecs() {
        Specification<BookEntity> surnameSort = AppBookSpecification.orderByAuthorSurname(false);
        Specification<BookEntity> hasFile = AppBookSpecification.hasDigitalFile();

        Specification<BookEntity> combined = hasFile.and(surnameSort);
        assertNotNull(combined, "Composed specification should not be null");
    }

    @Test
    void combine_withAuthorSort_doesNotThrow() {
        Specification<BookEntity> combined = AppBookSpecification.combine(
                AppBookSpecification.notDeleted(),
                AppBookSpecification.hasDigitalFile(),
                AppBookSpecification.orderByAuthorName(true)
        );
        assertNotNull(combined);
    }

    @Test
    void combine_withAuthorSurnameSort_doesNotThrow() {
        Specification<BookEntity> combined = AppBookSpecification.combine(
                AppBookSpecification.notDeleted(),
                AppBookSpecification.hasDigitalFile(),
                AppBookSpecification.orderByAuthorSurname(false)
        );
        assertNotNull(combined);
    }
}
